import type { GroupBy, TemplateInfo } from "../api/types";

export const PROBLEM_LABELS = [
  "Положительный / нейтральный отзыв",
  "Проблема с размером / посадкой",
  "Проблема с качеством товара",
  "Проблема с комплектацией / упаковкой",
  "Несоответствие карточке товара",
  "Цена / ценность",
  "Проблема с возвратом",
  "Проблема доставки / получения",
  "Другая проблема",
];

export const GROUP_BY_OPTIONS: Array<{ value: GroupBy; label: string }> = [
  { value: "day", label: "По дням" },
  { value: "week", label: "По неделям" },
  { value: "month", label: "По месяцам" },
];

export const QUICK_ANALYTICS_TEMPLATES: TemplateInfo[] = [
  {
    id: "count_by_problem",
    title: "Количество отзывов по проблеме",
    description: "Считает отзывы по выбранной проблеме и фильтрам.",
    default_answer_mode: "template",
    allow_llm_summary: true,
    needs_semantic_query: false,
    label_mode: "required",
    keyword_mode: "hidden",
  },
  {
    id: "top_problems",
    title: "Топ проблем",
    description: "Показывает самые частые проблемы. Фильтр по проблемам включается отдельно.",
    default_answer_mode: "template",
    allow_llm_summary: true,
    needs_semantic_query: false,
    label_mode: "subset",
    keyword_mode: "hidden",
    default_group_by: "label",
  },
  {
    id: "problem_dynamics",
    title: "Динамика проблемы",
    description: "Строит динамику проблем по дням, неделям или месяцам.",
    default_answer_mode: "template",
    allow_llm_summary: true,
    needs_semantic_query: false,
    label_mode: "subset",
    keyword_mode: "hidden",
    default_group_by: "week",
  },
  {
    id: "review_samples",
    title: "Примеры отзывов",
    description: "Показывает тексты отзывов по фильтрам, проблемам или ключевому слову.",
    default_answer_mode: "template",
    allow_llm_summary: true,
    needs_semantic_query: false,
    label_mode: "optional",
    keyword_mode: "optional",
  },
  {
    id: "review_examples",
    title: "RAG: похожие отзывы",
    description: "Ищет похожие отзывы по смыслу через Qdrant и готовит примеры для объяснения.",
    default_answer_mode: "llm",
    allow_llm_summary: true,
    needs_semantic_query: true,
    label_mode: "optional",
    keyword_mode: "required",
  },
  {
    id: "top_products_by_problem",
    title: "Топ товаров по проблеме",
    description: "Находит товары, где чаще всего встречаются выбранные проблемы.",
    default_answer_mode: "template",
    allow_llm_summary: true,
    needs_semantic_query: false,
    label_mode: "optional",
    keyword_mode: "hidden",
    default_group_by: "product",
  },
  {
    id: "period_comparison",
    title: "Сравнение периодов",
    description: "Сравнивает выбранный период с предыдущим равным периодом.",
    default_answer_mode: "template",
    allow_llm_summary: true,
    needs_semantic_query: false,
    label_mode: "subset",
    keyword_mode: "optional",
    default_group_by: "label",
  },
  {
    id: "problem_share",
    title: "Доли проблем",
    description: "Показывает долю каждой проблемы среди отзывов по фильтрам.",
    default_answer_mode: "template",
    allow_llm_summary: true,
    needs_semantic_query: false,
    label_mode: "subset",
    keyword_mode: "hidden",
    default_group_by: "label",
  },
  {
    id: "problem_growth",
    title: "Рост проблем",
    description: "Показывает проблемы, которые сильнее всего выросли к прошлому периоду.",
    default_answer_mode: "template",
    allow_llm_summary: true,
    needs_semantic_query: false,
    label_mode: "subset",
    keyword_mode: "optional",
    default_group_by: "label",
  },
  {
    id: "label_cooccurrence",
    title: "Совместные проблемы",
    description: "Показывает пары проблем, которые часто встречаются в одном отзыве.",
    default_answer_mode: "template",
    allow_llm_summary: true,
    needs_semantic_query: false,
    label_mode: "subset",
    keyword_mode: "hidden",
  },
  {
    id: "keyword_search",
    title: "Поиск по слову",
    description: "Ищет отзывы по слову или фразе через PostgreSQL.",
    default_answer_mode: "template",
    allow_llm_summary: true,
    needs_semantic_query: false,
    label_mode: "optional",
    keyword_mode: "required",
  },
  {
    id: "positive_vs_problem",
    title: "Положительные против проблемных",
    description: "Считает долю положительных/нейтральных и проблемных отзывов во времени.",
    default_answer_mode: "template",
    allow_llm_summary: true,
    needs_semantic_query: false,
    label_mode: "hidden",
    keyword_mode: "hidden",
    default_group_by: "month",
  },
];
